name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_DEPLOY_KEY }} # Gunakan token akses di sini

    - name: Set up Git
      run: |
        git config --global user.email "you@example.com" # Ganti dengan email Anda
        git config --global user.name "Your Name" # Ganti dengan nama Anda

    - name: Build and Test
      run: |
        # Command untuk membangun dan menguji proyek Anda
        echo "Building and Testing"
